#!/bin/bash

export ADMIN_COMMAND="$1"
shift
#docker tag $REPO/$IMAGE:$VERSION docker.pkg.github.com/$OWNER/$REPO/$IMAGE:$VERSION
#docker tag $REPO/$IMAGE:$VERSION docker.pkg.github.com/$OWNER/$REPO/$IMAGE:latest

export DANAKE_VERSION="0.1.0-beta"

case "$ADMIN_COMMAND" in

    start)
      #docker stack deploy -c base.yml base
      docker stack deploy -c danake.yml danake
    ;;

    stop)
      docker stack rm danake
      #docker stack rm base
    ;;

    build)
      docker-compose -f build.yml build
      docker-compose -f build.yml push
    ;;

    setup)
        mkdir -p ./data/{logs,pictures,registry}
    ;;

    *)
        echo "danake-admin: command '$ADMIN_COMMAND' not recognized" >&2
        exit 1
esac
