version: "3.8"
services:

  registry:
    image: registry:2
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - target: 5000
        published: 5000
    volumes:
      - type: volume
        source: registry_data
        target: /var/lib/registry

  agent:
    image: portainer/agent
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /var/lib/docker/volumes
        target: /var/lib/docker/volumes
    networks:
      - agent_network

  portainer:
    image: portainer/portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify --ssl --sslcert /run/secrets/fullchain.pem --sslkey /run/secrets/privkey.pem
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    ports:
      - target: 8000 # ssh tunnel
        published: 8000
      - target: 9000
        published: 9000
    volumes:
      - type: volume
        source: portainer_data
        target: /data
    networks:
      - agent_network
    secrets:
      - fullchain.pem
      - privkey.pem

networks:
  agent_network:
    driver: overlay
    attachable: true

volumes:
  portainer_data:
  registry_data:

secrets:
  fullchain.pem:
    file: "${DANAKE_CONFS}/certs/fullchain.pem"
  privkey.pem:
    file: "${DANAKE_CONFS}/certs/privkey.pem"
