version: "3.8"
services:

  router:
    image: "${DANAKE_REGISTRY}/router:${DANAKE_VERSION:-latest}"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    ports:
      - target: 80
        published: 80
      - target: 443
        published: 443
    volumes:
      - type: bind
        source: "${DANAKE_DATA}/logs"
        target: /logs
      - type: bind
        source: "${DANAKE_CONFS}/cookie2uid.tsv"
        target: /cookie2uid.tsv
    networks:
      - backend_network
    secrets:
      - fullchain.pem
      - privkey.pem
      - dhparam.pem

  auth:
    image: "${DANAKE_REGISTRY}/auth:${DANAKE_VERSION:-latest}"
    user: "${DANAKE_UID}:${DANAKE_GID}"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    volumes:
      - type: bind
        source: "${DANAKE_DATA}/pictures"
        target: /pictures
      - type: bind
        source: "${DANAKE_CONFS}/uid2info.tsv"
        target: /uid2info.tsv
      - type: bind
        source: "${DANAKE_CONFS}/cookie2uid.tsv"
        target: /cookie2uid.tsv
    networks:
      - backend_network
    secrets:
      - source: auth-config.py
        target: /config.py

networks:
  backend_network:
    driver: overlay
    attachable: true

secrets:
  fullchain.pem:
    file: "${DANAKE_CONFS}/certs/fullchain.pem"
  privkey.pem:
    file: "${DANAKE_CONFS}/certs/privkey.pem"
  dhparam.pem:
    file: "${DANAKE_CONFS}/certs/dhparam.pem"
  auth-config.py:
    file: "${DANAKE_CONFS}/auth-config.py"
