version: "3.8"
services:

  reverse-proxy:
    image: "127.0.0.1:5000/danake/reverse-proxy:${DANAKE_VERSION:-latest}"
    ports:
      - "80:80"
      - "443:443"
    deploy:
      placement:
        constraints:
          - "node.role==manager"
    secrets:
      - fullchain.pem
      - privkey.pem
      - dhparam.pem
    volumes:
      - type: bind
        source: ./data/logs
        target: /logs
      - type: bind
        source: ./confs/reverse-proxy/cookie_map.tsv
        target: /cookie_map.tsv

  auth-app:
    image: "127.0.0.1:5000/danake/auth-app:${DANAKE_VERSION:-latest}"
    deploy:
      placement:
        constraints:
          - "node.role==manager"
    configs:
      - uid2info.tsv
    secrets:
      - source: auth-app-config.py
        target: /auth-app-config.py
    volumes:
      - type: bind
        source: ./data/pictures
        target: /pictures

  code-server:
    image: "127.0.0.1:5000/danake/code-server:${DANAKE_VERSION:-latest}"

configs:
  uid2info.tsv:
    file: ./confs/auth-app/uid2info.tsv

secrets:
  fullchain.pem:
    file: ./confs/reverse-proxy/certs/fullchain.pem
  privkey.pem:
    file: ./confs/reverse-proxy/certs/privkey.pem
  dhparam.pem:
    file: ./confs/reverse-proxy/dhparam.pem
  auth-app-config.py:
    file: ./confs/auth-app/conf.py

