#!/usr/bin/env python3

from csv import reader
from pathlib import Path
from secrets import token_urlsafe

UID2INFO_PATH = 'confs/uid2info.tsv'
UID2COOKIE_PATH = 'confs/uid2cookie.tsv'

UID2INFO = dict(reader(Path(UID2INFO_PATH).open('r'), delimiter = '\t'))

Path(UID2COOKIE_PATH).write_text('\n'.join(
  f'{uid}\t{token_urlsafe(32)}' for uid in UID2INFO
))
