version: "3.8"
services:

  router:
    image: "${DANAKE_REGISTRY}/router:${DANAKE_VERSION:-latest}"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    ports:
      - target: 80
        published: 80
      - target: 443
        published: 443
    volumes:
      - type: volume
        source: router_logs
        target: /logs
    networks:
      - editor_network
    secrets:
      - fullchain.pem
      - privkey.pem
      - dhparam.pem
      - source: cookie2uid.map
        target: /cookie2uid.map

  auth:
    image: "${DANAKE_REGISTRY}/auth:${DANAKE_VERSION:-latest}"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    volumes:
      - type: volume
        source: auth_pictures
        target: /pictures
    networks:
      - editor_network
    configs:
      - source: uid2info.tsv
        target: /uid2info.tsv
    secrets:
      - source: auth-config.py
        target: /config.py
      - source: cookie2uid.map
        target: /cookie2uid.map

networks:
  editor_network:
    driver: overlay
    attachable: true

configs:
  uid2info.tsv:
    file: "${DANAKE_CONFS}/uid2info.tsv"

volumes:
  router_logs:
  auth_pictures:

secrets:
  fullchain.pem:
    external: true
    name: danake_fullchain
  privkey.pem:
    external: true
    name: danake_privkey
  dhparam.pem:
    external: true
    name: danake_dhparam
  auth-config.py:
    external: true
    name: danake_auth_config
  cookie2uid.map:
    external: true
    name: danake_cookie2uid
